^{:nextjournal.clerk/visibility {:code :hide}
  :nextjournal.clerk/toc true}
(ns hugsql.overview
  (:require [nextjournal.clerk :as clerk]))

;; # HugSQL 笔记目录
;; 本页汇总 `notebooks/hugsql/` 下各笔记及作用, 便于快速导航。

(clerk/md "# HugSQL 笔记目录\n\n## 目录映射 (org 样式)\n\n* 安装\n  - [install.clj](install.clj)\n* Getting Started\n  - Start with SQL: [getting_sql.clj](getting_sql.clj) (配套 [playground.sql](../../resources/hugsql/playground.sql))\n  - Now Some Clojure: [getting_clj.clj](getting_clj.clj)\n* 使用 HugSQL\n  - def-db-fns: [getting_clj.clj](getting_clj.clj), [usage_fns.clj](usage_fns.clj)\n  - def-sqlvec-fns: [getting_clj.clj](getting_clj.clj), [usage_fns.clj](usage_fns.clj)\n  - Other Useful Functions: [usage_fns.clj](usage_fns.clj)\n  - DDL (Create/Drop): [crud.clj](crud.clj)\n  - Insert/Update/Delete/Select: [crud.clj](crud.clj)\n  - Transactions: [transactions.clj](transactions.clj)\n  - Composability: [composability.clj](composability.clj)\n    - Clojure Expressions: [composability.clj](composability.clj)\n    - Snippets: [composability.clj](composability.clj)\n  - Advanced Usage: [advanced_usage.clj](advanced_usage.clj)\n* 深入介绍\n  - SQL File Conventions: [getting_sql.clj](getting_sql.clj), [deep_dive.clj](deep_dive.clj)\n  - Command/Result: [deep_dive.clj](deep_dive.clj)\n  - Parameter Types: [deep_dive.clj](deep_dive.clj), [composability.clj](composability.clj)\n    - SQL Value/Value List/Tuple/Tuple List: [deep_dive.clj](deep_dive.clj), [crud.clj](crud.clj)\n    - Identifier/Identifier List: [deep_dive.clj](deep_dive.clj), [crud.clj](crud.clj)\n    - Raw SQL: [advanced_usage.clj](advanced_usage.clj)\n    - Snippet/Snippet List: [composability.clj](composability.clj)\n\n## 支撑与导航\n- 公共初始化: [common.clj](common.clj)\n- FAQ/对比: [faq.clj](faq.clj)\n- 适配器切换: [adapters.clj](adapters.clj)\n")
